experiment:
  name: "alt_attr_prompt"
  output_dir: "./results/ablations/alternative_attribution_prompt/"
  seed: 42
  max_token_budget: 10000000
  optimizer: "cantante"
  node_optimizer: "CAPO"
  selector: "naive"
  block_size: 10
  eval_strategy: "random_block"
  n_fs: 0
  attributer: "unconstrained"
  eval_timeout_sec: 180
  recursion_limit: 30
  dataset: "gsm8k"
  max_tokens_per_field: 128
  n_steps: 100 # stopped by callbacks

optimizer_kwargs:
  max_n_blocks_eval: 5
  length_penalty: 0.05
  crossovers_per_iter: 3
  alpha: 0.2
  upper_shots: 0

attributer_kwargs:
  group_size: 3
  use_alternative_attribution_prompt: true

task_llm_kwargs:
  model: "qwen-30b-a3b-llmlb"
  base_url: "https://openwebui.uni-freiburg.de/api"
  model_provider: "openai"
  max_tokens: 512
  temperature: 0.7
  requests_per_second: 4
  max_bucket_size: 4
  timeout: 100
  max_retries: 3

meta_llm_kwargs:
  model: "gpt-oss-120b-llmlb"
  base_url: "https://openwebui.uni-freiburg.de/api"
  model_provider: "openai"
  max_tokens: 4096
  temperature: 0.1
  requests_per_second: 2
  max_bucket_size: 1
  timeout: 180
  max_retries: 3

setup_dict_folder: "configs/setups"
